name: Build and Release Traefik Proxmox Provider

on:
  push:
    tags:
      - 'v1.0.0'  # Trigger the release on tag v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod tidy

      - name: Build provider
        run: go build -o traefik-proxmox-provider

      - name: Create release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: traefik-proxmox-provider
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
