name: Build and Release Traefik Proxmox Provider

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'  # Adjust the Go version to match your go.mod file

      - name: Install dependencies
        run: go mod tidy

      - name: Build provider
        run: go build -o traefik-proxmox-provider

      - name: Create Git tag
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: traefik-proxmox-provider
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

