name: Build and Release Traefik Proxmox Provider

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Manually triggerable workflow
  release:
    types:
      - created  # Trigger the release job when a tag is created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod tidy

      - name: Build provider
        run: go build -o traefik-proxmox-provider

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: traefik-proxmox-provider
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

