name: Build and Release Traefik Proxmox Provider

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod tidy

      - name: Build provider
        run: go build -o traefik-proxmox-provider

      - name: Create GitHub release
        uses: gh-actions/release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: "v1.0.0"
          body: "Release v1.0.0"
          draft: false
          prerelease: false

      - name: Upload provider binary as asset
        uses: softprops/action-gh-release@v1
        with:
          files: traefik-proxmox-provider
